# Everything in this section will be available as an environment variable
db_username = "mikeryoma"
db_password = "123456789"
REPLICATE_API_TOKEN="r8_REeMOWQm2wE65OQvyC7OZNQp2xTfrd72MXtC4"
# You can also add other sections if you like.
# The contents of sections as shown below will not become env variables,but they'll be easily accessible from within Streamlit anyway as we show later in this doc.
[my_cool_secrets]
things_i_like = ["Streamlit", "Python"]